### ISSUE TITLE
Remove tidyverse-meta-package structure

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/fgeo#78]
RE #76.

- [ ] Disconnect hidden moudles from .onAttach
- [ ] Remove unecessary dependencies used to manage meta-package (cli, crayon, rstudioapi?)
- [ ] Use `@family` fgeo functions to create a section in References for fgeo.
